### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by LuuHuy** [tarlepp/angular-material-webpack-seed#2]
Hi,

Thanks for this seed, I have been playing around with this but I got an error after run `npm run dev-server`

And here is the output

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at linterResults (/opt/lampp/htdocs/projects/test-1/node_modules/scsslint-loader/dist/scsslint-loader.js:20:28)
    at /opt/lampp/htdocs/projects/test-1/node_modules/scsslint-loader/dist/scsslint-loader.js:57:13
    at ChildProcess.exithandler (child_process.js:259:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Socket.stream.socket.on (internal/child_process.js:340:11)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at Pipe._handle.close [as _onclose] (net.js:546:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-material-webpack-seed@0.0.0 build-dev: `webpack --config ./config/webpack.config.js --progress --profile --colors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-material-webpack-seed@0.0.0 build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/louis/.npm/_logs/2017-09-26T00_16_51_900Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-material-webpack-seed@0.0.0 dev-server: `npm run build-dev && webpack-dev-server --config config/webpack-dev-server.config.js --progress --colors --inline --content-base public`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-material-webpack-seed@0.0.0 dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I tried to update the scsslint lib but did not help

Any idea? Or do you have any plan to update this seed (newer webpack and other libs)

Thanks

**Comment by Alex-Golovin** [comment]
+1 same issue
